services:

  grants-analytics-db:
    image: postgres:15-alpine
    container_name: grants-analytics-db
    command: postgres -c "log_lock_waits=on" -N 1000 -c "fsync=off"
    env_file: ./local.env
    ports:
      - "5433:5432"
    volumes:
      - grantsanalyticsdbdata:/var/lib/postgresql/data

  grants-analytics:
    build:
      context: .
      target: dev
      args:
        - RUN_UID=${RUN_UID:-4000}
        - RUN_USER=${RUN_USER:-analytics}
    container_name: grants-analytics
    env_file: ./local.env
    volumes:
      - .:/analytics
      - ~/.ssh:/home/${RUN_USER:-analytics}/.ssh
    depends_on:
      - grants-analytics-db

  grants-metabase:
    image: metabase/metabase:latest
    container_name: grants-metabase
    volumes:
    - /dev/urandom:/dev/random:ro
    ports:
      - 3100:3000
    env_file: ./local.env

volumes:
  grantsanalyticsdbdata:
