services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    restart: always
    ports:
      - 8888:8080
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  nextjs:
    container_name: next-dev
    platform: linux/amd64
    build:
      context: .
      target: release
    env_file:
      - ./.env.local
    volumes:
      - ./src:/frontend/src
      - ./public:/frontend/public
    restart: always
    ports:
      - 3000:3000
