services:
  nextjs:
    container_name: next-dev
    platform: linux/amd64
    build:
      context: .
      target: dev
    env_file:
      - ./.env.development
    volumes:
      - ./src:/frontend/src
      - ./public:/frontend/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - default
      - api_grants_backend

  storybook:
    container_name: storybook
    platform: linux/amd64
    build:
      context: .
      target: dev
    command: npm run storybook
    volumes:
      - ./src:/frontend/src
      - ./public:/frontend/public
      - ./.storybook:/frontend/.storybook
      - ./stories:/frontend/stories
    restart: always
    ports:
      - 6006:6006
    networks:
      - default

  mock-oauth2-server:
    image: pavitt/mock-oauth2-server:0.3.5
    ports:
      - "5000:5000"
    environment:
      LOG_LEVEL: "debug"
      SERVER_PORT: 5000
      JSON_CONFIG_PATH: /app/config.json
      ISSUER_ID: http:localhost:5000
    networks:
      - default
      - api_grants_backend

networks:
  api_grants_backend:
    external: true
