info:
  description: '

    Back end API for simpler.grants.gov.


    This API is an ALPHA VERSION! Its current form is primarily for testing and feedback.
    Features are still under heavy development, and subject to change. Not for production
    use.


    See [Release Phases](https://github.com/github/roadmap?tab=readme-ov-file#release-phases)
    for further details.

    '
  contact:
    name: Simpler Grants.gov
    url: https://simpler.grants.gov/
    email: simplergrantsgov@hhs.gov
  title: Simpler Grants API
  version: v0
tags:
- name: Health
- name: Opportunity
paths:
  /health:
    get:
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The message to return
                  data:
                    $ref: '#/components/schemas/Healthcheck'
                  status_code:
                    type: integer
                    description: The HTTP status code
                  pagination_info:
                    description: The pagination information for paginated endpoints
                    type: &id001
                    - object
                    allOf:
                    - $ref: '#/components/schemas/PaginationInfo'
                  warnings:
                    type: array
                    items:
                      type: &id002
                      - object
                      allOf:
                      - $ref: '#/components/schemas/ValidationIssue'
          description: Successful response
        '503':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The message to return
                  data:
                    $ref: '#/components/schemas/ErrorResponse'
                  status_code:
                    type: integer
                    description: The HTTP status code
                  pagination_info:
                    description: The pagination information for paginated endpoints
                    type: *id001
                    allOf:
                    - $ref: '#/components/schemas/PaginationInfo'
                  warnings:
                    type: array
                    items:
                      type: *id002
                      allOf:
                      - $ref: '#/components/schemas/ValidationIssue'
          description: Service Unavailable
      tags:
      - Health
      summary: Health
  /v0/opportunities/search:
    post:
      parameters:
      - in: header
        name: FF-Enable-Opportunity-Log-Msg
        description: Whether to log a message in the opportunity endpoint
        schema:
          type: boolean
        required: false
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The message to return
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Opportunity'
                  status_code:
                    type: integer
                    description: The HTTP status code
                  pagination_info:
                    description: The pagination information for paginated endpoints
                    type: &id003
                    - object
                    allOf:
                    - $ref: '#/components/schemas/PaginationInfo'
                  warnings:
                    type: array
                    items:
                      type: &id004
                      - object
                      allOf:
                      - $ref: '#/components/schemas/ValidationIssue'
          description: Successful response
        '422':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The message to return
                  data:
                    $ref: '#/components/schemas/ErrorResponse'
                  status_code:
                    type: integer
                    description: The HTTP status code
                  pagination_info:
                    description: The pagination information for paginated endpoints
                    type: *id003
                    allOf:
                    - $ref: '#/components/schemas/PaginationInfo'
                  warnings:
                    type: array
                    items:
                      type: *id004
                      allOf:
                      - $ref: '#/components/schemas/ValidationIssue'
          description: Validation error
        '401':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The message to return
                  data:
                    $ref: '#/components/schemas/ErrorResponse'
                  status_code:
                    type: integer
                    description: The HTTP status code
                  pagination_info:
                    description: The pagination information for paginated endpoints
                    type: *id003
                    allOf:
                    - $ref: '#/components/schemas/PaginationInfo'
                  warnings:
                    type: array
                    items:
                      type: *id004
                      allOf:
                      - $ref: '#/components/schemas/ValidationIssue'
          description: Authentication error
      tags:
      - Opportunity
      summary: Opportunity Search
      description: '

        __ALPHA VERSION__


        This endpoint in its current form is primarily for testing and feedback.


        Features in this endpoint are still under heavy development, and subject to
        change. Not for production use.


        See [Release Phases](https://github.com/github/roadmap?tab=readme-ov-file#release-phases)
        for further details.

        '
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OpportunitySearch'
      security:
      - ApiKeyAuth: []
  /v0/opportunities/{opportunity_id}:
    get:
      parameters:
      - in: path
        name: opportunity_id
        schema:
          type: integer
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The message to return
                  data:
                    $ref: '#/components/schemas/Opportunity'
                  status_code:
                    type: integer
                    description: The HTTP status code
                  pagination_info:
                    description: The pagination information for paginated endpoints
                    type: &id005
                    - object
                    allOf:
                    - $ref: '#/components/schemas/PaginationInfo'
                  warnings:
                    type: array
                    items:
                      type: &id006
                      - object
                      allOf:
                      - $ref: '#/components/schemas/ValidationIssue'
          description: Successful response
        '401':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The message to return
                  data:
                    $ref: '#/components/schemas/ErrorResponse'
                  status_code:
                    type: integer
                    description: The HTTP status code
                  pagination_info:
                    description: The pagination information for paginated endpoints
                    type: *id005
                    allOf:
                    - $ref: '#/components/schemas/PaginationInfo'
                  warnings:
                    type: array
                    items:
                      type: *id006
                      allOf:
                      - $ref: '#/components/schemas/ValidationIssue'
          description: Authentication error
        '404':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The message to return
                  data:
                    $ref: '#/components/schemas/ErrorResponse'
                  status_code:
                    type: integer
                    description: The HTTP status code
                  pagination_info:
                    description: The pagination information for paginated endpoints
                    type: *id005
                    allOf:
                    - $ref: '#/components/schemas/PaginationInfo'
                  warnings:
                    type: array
                    items:
                      type: *id006
                      allOf:
                      - $ref: '#/components/schemas/ValidationIssue'
          description: Not found
      tags:
      - Opportunity
      summary: Opportunity Get
      description: '

        __ALPHA VERSION__


        This endpoint in its current form is primarily for testing and feedback.


        Features in this endpoint are still under heavy development, and subject to
        change. Not for production use.


        See [Release Phases](https://github.com/github/roadmap?tab=readme-ov-file#release-phases)
        for further details.

        '
      security:
      - ApiKeyAuth: []
openapi: 3.1.0
components:
  schemas:
    PaginationInfo:
      type: object
      properties:
        page_offset:
          type: integer
          description: The page number that was fetched
          example: 1
        page_size:
          type: integer
          description: The size of the page fetched
          example: 25
        total_records:
          type: integer
          description: The total number of records fetchable
          example: 42
        total_pages:
          type: integer
          description: The total number of pages that can be fetched
          example: 2
        order_by:
          type: string
          description: The field that the records were sorted by
          example: id
        sort_direction:
          description: The direction the records are sorted
          enum:
          - ascending
          - descending
          type:
          - string
    ValidationIssue:
      type: object
      properties:
        type:
          type: string
          description: The type of error
        message:
          type: string
          description: The message to return
        field:
          type: string
          description: The field that failed
    Healthcheck:
      type: object
      properties:
        message:
          type: string
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: The message to return
        data:
          description: The REST resource object
        status_code:
          type: integer
          description: The HTTP status code
        errors:
          type: array
          items:
            type:
            - object
            allOf:
            - $ref: '#/components/schemas/ValidationIssue'
    OpportunitySorting:
      type: object
      properties:
        order_by:
          type: string
          enum:
          - opportunity_id
          - agency
          - opportunity_number
          - created_at
          - updated_at
          description: The field to sort the response by
        sort_direction:
          description: Whether to sort the response ascending or descending
          enum:
          - ascending
          - descending
          type:
          - string
      required:
      - order_by
      - sort_direction
    Pagination:
      type: object
      properties:
        page_size:
          type: integer
          minimum: 1
          description: The size of the page to fetch
          example: 25
        page_offset:
          type: integer
          minimum: 1
          description: The page number to fetch, starts counting from 1
          example: 1
      required:
      - page_offset
      - page_size
    OpportunitySearch:
      type: object
      properties:
        opportunity_title:
          type: string
          description: The title of the opportunity to search for
          example: research
        category:
          description: The opportunity category to search for
          example: !!python/object/apply:src.constants.lookup_constants.OpportunityCategory
          - D
          enum:
          - D
          - M
          - C
          - E
          - O
          type:
          - string
        sorting:
          type:
          - object
          allOf:
          - $ref: '#/components/schemas/OpportunitySorting'
        paging:
          type:
          - object
          allOf:
          - $ref: '#/components/schemas/Pagination'
      required:
      - paging
      - sorting
    Opportunity:
      type: object
      properties:
        opportunity_id:
          type: integer
          readOnly: true
          description: The internal ID of the opportunity
          example: 12345
        opportunity_number:
          type: string
          description: The funding opportunity number
          example: ABC-123-XYZ-001
        opportunity_title:
          type: string
          description: The title of the opportunity
          example: Research into conservation techniques
        agency:
          type: string
          description: The agency who created the opportunity
          example: US-ABC
        category:
          description: The opportunity category
          example: !!python/object/apply:src.constants.lookup_constants.OpportunityCategory
          - D
          enum:
          - D
          - M
          - C
          - E
          - O
          type:
          - string
        category_explanation:
          type: string
          description: Explanation of the category when the category is 'O' (other)
          example: null
        revision_number:
          type: integer
          description: The current revision number of the opportunity, counting starts
            at 0
          example: 0
        modified_comments:
          type: string
          description: Details regarding what modification was last made
          example: null
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Auth

