name: Deploy Analytics Infra
# Todo: create a composite action
on:
  push:
    branches:
      - main
    paths:
      - "infra/analytics/**"

jobs:
  build-repository:
    name: Build Repository
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.1
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: ./.github/actions/configure-aws-credentials
        with:
          app_name: analytics
          environment: shared
      - name: Build Repository
        run: |
          ./bin/terraform-init-and-apply.sh infra/analytics/build-repository shared

  deploy-infra:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ["database", "service"]
        envs: [ "dev"]
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.1
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: ./.github/actions/configure-aws-credentials
        with:
          app_name: analytics
          environment: shared

      - name: Terraform Init and Apply
        run: |
          export TF_CLI_ARGS="-input=false -auto-approve" 
          ./bin/terraform-init-and-apply.sh infra/analytics/${{ matrix.directory }} ${{ matrix.envs }}
