name: Deploy API
run-name: Deploy ${{ github.ref_name }} to API ${{ inputs.environment || (github.event_name == 'release' && 'prod') || 'nonprod' }}

on:
  push:
    branches:
      - "main"
      - "chouinar/2327-api-opensearch"
    paths:
      - "api/**"
      - ".github/**"
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: "target environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:

  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy.yml
    strategy:
      max-parallel: 1
      matrix:
        envs: [ "dev" ]
    with:
      app_name: "api"
      environment: ${{ matrix.envs }}
