name: Deploy API
run-name: Deploy ${{ github.ref_name }} to API ${{ inputs.environment || (github.event_name == 'release' && 'prod') || 'nonprod' }}

on:
  push:
    branches:
      - "main"
    paths:
      - "api/**"
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: "target environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  api-checks:
    name: Run API Checks
    uses: ./.github/workflows/ci-api.yml

  vulnerability-scans:
    name: Vulnerability Scans
    uses: ./.github/workflows/vulnerability-scans.yml
    with:
      app_name: api

  deploy:
    name: Deploy
    needs: [api-checks, vulnerability-scans]
    uses: ./.github/workflows/deploy.yml
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        envs: ${{ fromJSON(inputs.environment != null && format('["{0}"]', inputs.environment) || github.event_name == 'release' && '["prod"]' || github.ref_name == 'main' && '["dev", "staging"]' || '["dev"]')  }}
    with:
      app_name: "api"
      environment: ${{ matrix.envs }}

  send-slack-notification:
    if: failure()
    needs: [api-checks, vulnerability-scans, deploy]
    uses: ./.github/workflows/send-slack-notification.yml
    secrets: inherit
