name: Deploy Frontend Infra

on:
  push:
    branches:
      - main
    paths:
      - "infra/frontend/**"

jobs:
  deploy-infra:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ["database", "service"]
        envs: [ "staging", "prod"]
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.1
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: ./.github/actions/configure-aws-credentials
        with:
          app_name: frontend
          environment: shared

      - name: Build Repository
        run: |
          ./bin/terraform-init-and-apply.sh infra/frontend/build-repository shared

      - name: Terraform Init and Apply
        run: |
          TF_CLI_ARGS="-input=false -auto-approve" 
          ./bin/terraform-init-and-apply.sh infra/frontend/${{ matrix.directory }} ${{ matrix.envs }}
