name: Deploy Frontend
# Need to set a default value for when the workflow is triggered from a git push
# which bypasses the default configuration for inputs
run-name: Deploy ${{ github.ref_name }} to Frontend ${{ inputs.environment || (github.event_name == 'release' && 'prod') || 'nonprod' }}
on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: "target environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  frontend-checks:
    name: Run Frontend Checks
    uses: ./.github/workflows/ci-frontend.yml

  deploy:
    # run build-and publish here so that both envs won't try to build the image 
    name: Deploy
    needs: frontend-checks
    uses: ./.github/workflows/deploy.yml
    strategy:
      matrix:
        envs: ${{ github.event_name == 'release' && fromJSON('["prod"]') || github.ref_name == 'main' && fromJSON('["dev"]') || fromJSON('["dev"]') }} # temporarily removing staging from matrix. See: https://github.com/HHS/simpler-grants-gov/issues/1919
    with:
      app_name: "frontend"
      environment: ${{ matrix.envs }}
