name: API Checks

on:
  workflow_call:
  pull_request:
    paths:
      - api/**
      - .github/workflows/ci-api.yml

defaults:
  run:
    working-directory: ./api

jobs:
  lint-test:
    name: API Lint, Format & Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Initialize the docker containers
        run: make init

      - name: Run format check
        run: make format-check

      - name: Run linting
        run: make lint

      - name: Check migrations up-to-date
        run: make db-check-migrations

      - name: Run security linting
        run: make lint-security

      - name: Start tests
        run: |
          make test-audit
          make test-coverage

  vulnerability-scans:
    name: Run API Vulnerability Scans
    uses: ./.github/workflows/vulnerability-scans.yml
    with:
      app_name: "api"
