# GitHub Actions CI workflow that runs vulnerability scans on the application's Docker image
# to ensure images built are secure before they are deployed.

name: CI Vulnerability Scans

on:
  pull_request:
    paths:
      - .grype.yml
      - .hadolint.yaml
      - .trivyignore
      - .github/workflows/ci-vulnerability-scans.yml

jobs:
  vulnerability-scans:
    name: Vulnerability Scans
    strategy:
      matrix:
        app_name: ["frontend", "api", "analytics"]
    uses: ./.github/workflows/vulnerability-scans.yml
    with:
      app_name: ${{ matrix.app_name }}

  send-slack-notification:
    name: Send Slack notification on failure
    runs-on: ubuntu-latest
    if: failure()
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_ALERTS_CHANNEL_ID }}
    steps:
      - name: Send Slack notification
        run: |
          curl -X POST -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
            -H "Content-Type: application/json" \
            --data '{
              "channel": "'"$SLACK_CHANNEL_ID"'",
              "text": ":x: *GitHub Actions Failure Alert*",
              "attachments": [
                {
                  "color": "#ff0000",
                  "title": "Workflow *${{ github.workflow }}* failed",
                  "fields": [
                    {
                      "title": "Repository",
                      "value": "${{ github.repository }}",
                      "short": true
                    },
                    {
                      "title": "Branch",
                      "value": "${{ github.ref_name }}",
                      "short": true
                    },
                    {
                      "title": "Commit",
                      "value": "${{ github.sha }}",
                      "short": true
                    },
                    {
                      "title": "Workflow URL",
                      "value": "${{ github.run_url }}"
                    }
                  ],
                  "footer": "GitHub Actions",
                  "footer_icon": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                  "ts": '$(date +%s)'
                }
              ]
            }' https://slack.com/api/chat.postMessage
