# GitHub Actions CI workflow that runs vulnerability scans on the application's Docker image
# to ensure images built are secure before they are deployed.

name: CI Vulnerability Scans

on:
  workflow_dispatch:
  schedule:
    # Run every day at (8am ET, 11am PT) right before the start of the workday
    - cron: "0 12 * * *"

jobs:
  vulnerability-scans:
    name: Vulnerability Scans
    strategy:
      matrix:
        app_name: ["frontend", "api", "analytics"]
    uses: ./.github/workflows/vulnerability-scans.yml
    with:
      app_name: ${{ matrix.app_name }}

  send-slack-notification:
    if: failure()
    uses: ./.github/workflows/send-slack-notification.yml
