# GitHub Actions CI workflow that runs vulnerability scans on the application's Docker image
# to ensure images built are secure before they are deployed.

name: CI Vulnerability Scans

on:
  workflow_dispatch:
  schedule:
    # Run every day at (8am ET, 11am PT) right before the start of the workday
    - cron: "0 12 * * *"

jobs:
  vulnerability-scans:
    name: Vulnerability Scans
    strategy:
      matrix:
        app_name: ["frontend", "api", "analytics"]
    uses: ./.github/workflows/vulnerability-scans.yml
    with:
      app_name: ${{ matrix.app_name }}

  send-slack-notification:
    name: Send Slack notification on failure
    needs: vulnerability-scans
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Send Slack notification
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.ALERTS_SLACK_BOT_TOKEN }}" \
          -H "Content-Type: application/json; charset=utf-8" \
          --data '{
            "channel": "${{ secrets.SLACK_ALERTS_CHANNEL_ID }}",
            "text": ":x: *GitHub Actions Failure Alert*",
            "attachments": [
            {
              "color": "#ff0000",
              "title": "Workflow *'"${{ github.workflow }}"'* failed",
              "fields": [
              {
                "title": "Workflow URL",
                "value": "'"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"'"
              }
              ],
              "footer": "GitHub Actions",
              "footer_icon": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              "ts": '$(date +%s)'
            }
            ]
          }' https://slack.com/api/chat.postMessage
