name: CI Project linters

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/linters/**
      - .github/workflows/ci-project-linters.yml

defaults:
  run:
    working-directory: ./.github/linters # ensures that this job runs from the ./linters sub-directory

jobs:
  dry-run-project-linters:
    name: Dry run GitHub project linters
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN_PROJECT_ACCESS }}
      # Test issue with points and sprint values unset
      # to be used with set-points-and-sprint.sh test
      UNSET_ISSUE: "https://github.com/HHS/simpler-grants-gov/issues/1932"
    steps:
      - uses: actions/checkout@v4

      - name: Dry run - Close open issues marked as "Done" in Sprint Board
        run: |
          ./scripts/close-issues-in-done-col.sh \
            --org HHS \
            --project 13 \
            --status Done \
            --batch 100 \
            --dry-run

      - name: Dry run - Set points and sprint field
        run: |
          ./scripts/set-points-and-sprint.sh \
            --url "${UNSET_ISSUE}" \
            --org "HHS" \
            --project 13 \
            --sprint-field "Sprint" \
            --points-field "Story Points" \
            --dry-run
