name: CI Project linters

on:
  workflow_dispatch:
  pull_request:
    paths:
      - linters/**
      - .github/workflows/ci-project-linters.yml

defaults:
  run:
    working-directory: ./linters # ensures that this job runs from the ./linters sub-directory

jobs:
  dry-run-project-linters:
    name: Dry run GitHub project linters
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN_PROJECT_ACCESS }}
    steps:
      # set up python
      - uses: actions/checkout@v3

      - name: Dry run - Close open issues marked as "Done" in Sprint Board
        run: |
          ORG="HHS"\
            PROJECT=13\
            STATUS="Done"\
            BATCH=100\
            ./scripts/close-issues-in-done-col.sh
