# GitHub Actions CI workflow that runs vulnerability scans on the application's Docker image
# to ensure images built are secure before they are deployed.

name: CI Vulnerability Scans

on:
  pull_request:
    paths:
      - .grype.yml
      - .hadolint.yaml
      - .trivyignore
      - .github/workflows/ci-vulnerability-scans.yml

jobs:
  vulnerability-scans:
    name: Vulnerability Scans
    strategy:
      matrix:
        app_name: ["frontend", "api", "analytics"]
    uses: ./.github/workflows/vulnerability-scans.yml
    with:
      app_name: ${{ matrix.app_name }}
