name: Deploy
# Need to set a default value for when the workflow is triggered from a git push,
# which bypasses the default configuration for inputs and cannot use env.ENVIRONMENT
# since env context is not accessible in this context
run-name: Deploy ${{ github.ref_name }} to ${{ inputs.environment || 'dev' }}

on:
  push:
    branches:
      - "main"
    paths:
      - "frontend/**"
      - "bin/**"
      - "infra/**"
  workflow_dispatch:
    inputs:
      app_name:
        description: "name of application folder under infra directory"
        default: frontend
        type: string
      environment:
        description: "target environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

env:
  # Need to set a default value for when the workflow is triggered from a git push,
  # which bypasses the default configuration for inputs
  APP_NAME: ${{ inputs.app_name || 'frontend' }}
  ENVIRONMENT: ${{ inputs.environment || 'dev' }}

# Need to repeat the expression since env.ENVIRONMENT is not accessible in this context
concurrency: cd-${{ inputs.environment || 'dev' }}

jobs:
  # Don't need to call the build-and-publish workflow since the database-migrations
  # workflow already calls it
  database-migrations:
    name: Database migrations
    uses: ./.github/workflows/database-migrations.yml
    with:
      app_name: ${{ inputs.app_name || 'frontend' }}
      environment: ${{ inputs.environment || 'dev' }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [database-migrations]
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: ./.github/actions/configure-aws-credentials
        with:
          app_name: ${{ env.APP_NAME }}
          environment: ${{ env.ENVIRONMENT }}

      - name: Deploy release
        run: make release-deploy APP_NAME=$APP_NAME ENVIRONMENT="$ENVIRONMENT"
