name: Deploy

on:
  workflow_call:
    inputs:
      app_name:
        description: "name of application folder under infra directory"
        required: true
        type: string
      environment:
        description: "the name of the application environment (e.g. dev, staging, prod)"
        required: true
        type: string

concurrency: cd-${{ inputs.environment }}

jobs:
  build-and-publish:
    name: Build
    uses: ./.github/workflows/build-and-publish.yml
    with:
      app_name: ${{ inputs.app_name }}
      ref: ${{ github.ref }}

  database-migrations:
    name: Database migrations
    uses: ./.github/workflows/database-migrations.yml
    with:
      app_name: ${{ inputs.app_name }}
      environment: ${{ inputs.environment }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [database-migrations]
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: ./.github/actions/configure-aws-credentials
        with:
          app_name: ${{ inputs.app_name }}
          environment: ${{ inputs.environment }}

      - name: Deploy release
        run: make release-deploy APP_NAME=${{ inputs.app_name }} ENVIRONMENT=${{ inputs.environment }}
