#
# GitHub action to add labels to pull requests.
#
# Label rules are configured in .github/labeler.xml.
#
# See https://github.com/marketplace/actions/labeler
#

name: Pull Request Labeler

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  label:
    name: Labeler
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5