name: Lint - Set points and sprint on close

on:
  # trigger on PRs that affect this file or a file used to run the linter
  issues:
    types: [closed]

defaults:
  run:
    working-directory: ./.github/linters # ensures that this job runs from the ./linters sub-directory

jobs:
  run-project-linters:
    name: Run set points and sprint values on close
    runs-on: ubuntu-22.04
    # Prevents duplicate runs of this linter for the same issue
    concurrency:
      group: issue-${{ github.event.issue.number }}
      cancel-in-progress: true
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN_PROJECT_ACCESS }}
      ISSUE_URL: ${{ github.event.issue.html_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Set default values for sprint and points if unset
        run: |
          ./scripts/set-points-and-sprint.sh \
            --url "$ISSUE_URL" \
            --org HHS \
            --project 13 \
            --sprint-field "Sprint" \
            --points-field "Story Points"
